spring:
  sql:
    init:
      schema-locations: classpath*:schema.sql
  r2dbc:
    url: r2dbc:h2:mem:///test
    username: sa
    password:
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG