DROP TABLE IF EXISTS DATA CASCADE;
CREATE TABLE DATA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    TITLE VARCHAR(255) NOT NULL ,
    CONTENT VARCHAR(1000) ,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    FIRST_INSERT_TIME TIME NOT NULL DEFAULT NOW(),
    LAST_UPDATED_TIME TIME NOT NULL DEFAULT NOW()
);

INSERT INTO DATA(TITLE,CONTENT,DELETED,FIRST_INSERT_TIME,LAST_UPDATED_TIME)
VALUES ('TITLE1','CONTENT1','N',NOW(),NOW());

INSERT INTO DATA(TITLE,CONTENT,DELETED,FIRST_INSERT_TIME,LAST_UPDATED_TIME)
VALUES ('TITLE2','CONTENT2','N',NOW(),NOW());

INSERT INTO DATA(TITLE,CONTENT,DELETED,FIRST_INSERT_TIME,LAST_UPDATED_TIME)
VALUES ('TITLE3','CONTENT3','N',NOW(),NOW());

INSERT INTO DATA(TITLE,CONTENT,DELETED,FIRST_INSERT_TIME,LAST_UPDATED_TIME)
VALUES ('TITLE4','CONTENT4','N',NOW(),NOW());

INSERT INTO DATA(TITLE,CONTENT,DELETED,FIRST_INSERT_TIME,LAST_UPDATED_TIME)
VALUES ('TITLE5','CONTENT5','N',NOW(),NOW());